In [1]:
import pandas as pd
import numpy as np
import os
import re
import psycopg

In [2]:
data = pd.read_csv("/Users/anshumaansoni/PycharmProjects/chrononexia/db/scripts/OC data (Responses) - Form Responses 1.csv")
display(data)

,Timestamp,Full Name,Your Position in Symbitech,Academic Year,"A comment you may want to give, related to the event. ( Like a yearbook comment, will be used on website and insta posts. )","Describe yourself in about 30 words, and why you're a great fit in the symbitech OC",Image
0,7/22/2026 20:19:39,Aarushi Sathyanarayanan,Fest Head,Third Year,We made it. Don't ask how. (OR) Every great id...,"Part planner, part problem-solver, full-time c...",5114
1,7/22/2026 22:55:28,Anirudh Singh,Design Head,Third Year,Glad to be a part of it!,"Creative, reliable, and proactive, I enjoy wor...",5511
2,7/22/2026 22:26:59,Anushka Gupta,Co head hospitality,Second Year,"To all the people, the chaos, and the memo...","I believe I am a great fit as I’m organized, d...",4449
3,7/23/2026 12:14:29,Arush Kapur,Fest Head,Third Year,Ctrl + Z doesn’t work in life. I checked !!,"I lead with initiative, stay calm under pressu...",5113
4,7/22/2026 11:40:44,Atharva Somawanshi,Executive Hospitality,Third Year,NaN,I can do this task as i was the executive for ...,Executive_Hospitality_Atharva Somawanshi
5,7/22/2026 11:46:14,Eklavya Singh Shekhawat,Executive member Logistics,Third Year,"Where ideas spark, technology inspires, and me...",Proactive team player who enjoys taking respon...,5140
6,7/22/2026 12:44:04,Ishaan Chand,Co Head,Second Year,Sleep is temporary. SymbiTech screenshots are ...,"I'm Ishaan, a student of AIML, who thrives on ...",5570
7,7/22/2026 22:12:17,Kavish Nag,Documentation Executive,Third Year,The best stories are yet to be written. Excite...,"I am someone who likes to stay involved, help ...",5122
8,7/22/2026 12:52:36,Kavya Prashant Ahire,Event Co-Head,Second Year,"Came for the tech, stayed for the chaos, and s...","I’m a people person who loves taking charge, b...",5552
9,7/27/2026 12:48:54,Kush Mittal,Design Head,Second Year,"Every late night, every challenge, every l...",Im my own toughest critic constantly refining ...,NaN
10,7/27/2026 14:27:36,Madhav Menaria,Hospitality executive,Third Year,Ye dil maange more attendance,"I play chess, run for fun and like making thin...",5120
11,7/22/2026 11:54:49,Madhur Sahay,Co-head logistics,Second Year,An event where tech and fun collides. Few days...,I have already volunteered for the event befor...,5503
12,7/27/2026 14:39:48,Mahek Mishra,Co-head Hospitality,Third Year,"“Some experiences become stories, and some sto...",I’m a proactive and dependable leader who enjo...,5488
13,7/23/2026 19:29:37,Mantavya Anand,Design Executive,Third Year,Why take the high road when the scenic one has...,"I say yes first, then spend the next few days ...",5121
14,7/22/2026 23:05:44,Mehar Jaspal,Documentation Co-head,Second Year,1. The only days that make still going to coll...,Im a great fit because I do my job quickly eno...,5493
15,7/27/2026 12:33:03,Mishti Kinker,Events Head,Third Year,"Not just an event, but a collection of laughte...","I'm someone who loves getting involved, meetin...",NaN
16,7/22/2026 23:42:08,Navya Joshi,Finance Executive,Third Year,"Less “YOLO,” more “ROI”.","I count memories, but I budget in rupees. Reli...",5133
17,7/27/2026 14:22:41,Nilay Bhatia,Fest Head,Third Year,You don’t realise you are living in the gold o...,You’ll see for yourself : )),5107
18,7/22/2026 22:27:40,Ninad Kulkarni,Executive Head Logistics,Third Year,NaN,As a third-year student and Executive Head of ...,5136
19,7/27/2026 14:11:27,Parth sarathi Giri,Hospitality head,Third Year,Onwards and upwards,"A dedicated learner who takes initiative, work...",HOSPITALITY HEAD PARTH
20,7/27/2026 11:38:07,Rachit Jajoo,Design Co-Head,Second Year,Ctrl + S your memories. You never know when yo...,Ideas are easy. Execution is everything. I bri...,NaN
21,7/22/2026 22:24:48,Revanth Sai Sreerangam,Co head finance,Third Year,Journey or destination? I choose people coz wh...,"Curious, patient, and people-oriented. I enjoy...",5478
22,7/22/2026 22:37:53,Samriddhi Chadha,Co-Head,Second Year,NaN,"I am very eager to interact, communicate, lead...",5510
23,7/22/2026 12:05:22,Shreyas wani,Finance co-head,Second Year,Build something worth remembering.\n,"I take ownership, stay dependable under pressu...",5469
24,7/22/2026 12:16:16,Shruti Hore,Design Co Head,Third Year,Core memory unlocked 🫶🫶,"Organized, creative, and always down to help. ...",5483
25,7/22/2026 15:32:39,Shubh Vishwanath Pachling,Finance Head,Third Year,NaN,Im a mechanical engineering student who likes ...,5517
26,7/24/2026 19:03:52,Siya Joshi,Events Co-Head,Third Year,You miss 100% of the shots you don’t take.,I think I’m a good fit for the SymbITech Organ...,5514
27,7/23/2026 11:29:17,Sparsh Srivastava,PR HEAD,Third Year,"Unfiltered,Unapologetic,Unmissable.","Student entrepreneur, Founder of CareSaathi, p...",Sparsh_Srivastava_Sponsorship&PR Head
28,7/22/2026 11:56:28,Suryansh Singh Rathod,Co-head Logistics,Second Year,"""We were the load balancers of Symbitech — kee...",One of the important character trait about me ...,5495
29,7/27/2026 14:28:09,Uday Pratap Gupta,"Co-Head, Sponsorship & PR",Second Year,\nCode. Create. Connect. Repeat. See you at Sy...,I am a Computer Science student who enjoys sol...,4955
30,7/22/2026 12:07:52,Uday pratap gupta,Co-head,Second Year,NaN,I am a hardworking and creative person. I like...,4955
31,7/23/2026 11:18:16,Vanya Puranik,Finance Co-head,Third Year,Great events aren’t remembered for being perfe...,"I’m a responsible, detail oriented, and collab...",5473
32,7/22/2026 11:52:11,Wani Kolhey,Website Head,Third Year,NaN,"Good design isn't just seen, it's experienced....",5522
33,7/22/2026 22:37:48,Yatharth Kaul,Executive member- events,Third Year,The event ends. The legacy doesn’t.,"I enjoy being involved, taking ownership, and ...",5132
34,7/28/2026 9:53:27,Vardhan Shah,"Co-Head - Sponsors, PR, Media",Third Year,"I don't count memories by days, I count them b...","I'm Vardhan Shah, co-head, PR & Sponsors team....",5461

In [3]:
# Clean up unnecessary timestamp column if present
if "Timestamp" in data.columns:
    data = data.drop(columns=["Timestamp"])

## Processing Image references and linking to actual photoshoot files

In [4]:
photoshoot_dir = "/Users/anshumaansoni/PycharmProjects/chrononexia/src/assets/Photoshoot"
list_dir = os.listdir(photoshoot_dir)

# Build matching lookup table for photoshoot filenames
file_map = {}
for f in list_dir:
    if f.startswith("."):
        continue
    base, ext = os.path.splitext(f)
    file_map[f.lower()] = f
    file_map[base.lower()] = f
    if base.lower().startswith("img_"):
        file_map[base[4:].lower()] = f

def resolve_image_path(raw_val):
    if pd.isna(raw_val):
        return None
    val_str = str(raw_val).strip()
    # Direct lookup
    if val_str.lower() in file_map:
        return f"src/assets/Photoshoot/{file_map[val_str.lower()]}"
    clean_val = val_str.replace("IMG_", "").lower()
    if clean_val in file_map:
        return f"src/assets/Photoshoot/{file_map[clean_val]}"
    # Partial substring lookup
    for key, fname in file_map.items():
        if clean_val == key or (len(clean_val) > 3 and clean_val in key):
            return f"src/assets/Photoshoot/{fname}"
    return None

data["Image_Path"] = data["Image"].apply(resolve_image_path)
display(data[["Full Name", "Image", "Image_Path"]])

,Full Name,Image,Image_Path
0,Aarushi Sathyanarayanan,5114,src/assets/Photoshoot/5114.JPG
1,Anirudh Singh,5511,src/assets/Photoshoot/5511.JPG
2,Anushka Gupta,4449,NaN
3,Arush Kapur,5113,src/assets/Photoshoot/5113.JPG
4,Atharva Somawanshi,Executive_Hospitality_Atharva Somawanshi,src/assets/Photoshoot/Executive_Hospitality_At...
5,Eklavya Singh Shekhawat,5140,src/assets/Photoshoot/5140.JPG
6,Ishaan Chand,5570,src/assets/Photoshoot/5570.JPG
7,Kavish Nag,5122,src/assets/Photoshoot/5122.JPG
8,Kavya Prashant Ahire,5552,src/assets/Photoshoot/5552.JPG
9,Kush Mittal,NaN,NaN
10,Madhav Menaria,5120,src/assets/Photoshoot/5120.JPG
11,Madhur Sahay,5503,src/assets/Photoshoot/5503.JPG
12,Mahek Mishra,5488,src/assets/Photoshoot/5488.JPG
13,Mantavya Anand,5121,src/assets/Photoshoot/5121.JPG
14,Mehar Jaspal,5493,src/assets/Photoshoot/5493.JPG
15,Mishti Kinker,NaN,NaN
16,Navya Joshi,5133,src/assets/Photoshoot/5133.JPG
17,Nilay Bhatia,5107,src/assets/Photoshoot/5107.JPG
18,Ninad Kulkarni,5136,src/assets/Photoshoot/5136.JPG
19,Parth sarathi Giri,HOSPITALITY HEAD PARTH,src/assets/Photoshoot/HOSPITALITY HEAD PARTH
20,Rachit Jajoo,NaN,NaN
21,Revanth Sai Sreerangam,5478,src/assets/Photoshoot/5478.JPG
22,Samriddhi Chadha,5510,src/assets/Photoshoot/5510.JPG
23,Shreyas wani,5469,src/assets/Photoshoot/5469.JPG
24,Shruti Hore,5483,src/assets/Photoshoot/5483.JPG
25,Shubh Vishwanath Pachling,5517,src/assets/Photoshoot/5517.JPG
26,Siya Joshi,5514,src/assets/Photoshoot/5514.JPG
27,Sparsh Srivastava,Sparsh_Srivastava_Sponsorship&PR Head,src/assets/Photoshoot/Sparsh_Srivastava_Sponso...
28,Suryansh Singh Rathod,5495,src/assets/Photoshoot/5495.JPG
29,Uday Pratap Gupta,4955,src/assets/Photoshoot/4955.JPG
30,Uday pratap gupta,4955,src/assets/Photoshoot/4955.JPG
31,Vanya Puranik,5473,src/assets/Photoshoot/5473.JPG
32,Wani Kolhey,5522,src/assets/Photoshoot/5522.JPG
33,Yatharth Kaul,5132,src/assets/Photoshoot/5132.JPG
34,Vardhan Shah,5461,src/assets/Photoshoot/5461.JPG

## Extracting Fest Heads, Executives, and Heads & Co-Heads

In [5]:
col_name = "Full Name"
col_pos = "Your Position in Symbitech"
col_year = "Academic Year"
col_comment = "A comment you may want to give, related to the event. ( Like a yearbook comment, will be used on website and insta posts. )"
col_desc = "Describe yourself in about 30 words, and why you're a great fit in the symbitech OC"
col_img = "Image_Path"

# 1. Fest Heads
fest_heads_df = data[data[col_pos].astype(str).str.strip().str.lower() == "fest head"].copy().reset_index(drop=True)

# 2. Executives
executives_df = data[data[col_pos].astype(str).str.contains("executive", case=False, na=False)].copy().reset_index(drop=True)

# 3. Heads & Co-Heads (excluding Fest Head & Executives)
exclude_mask = data[col_pos].astype(str).str.strip().str.lower().eq("fest head") | data[col_pos].astype(str).str.contains("executive", case=False, na=False)
heads_coheads_df = data[~exclude_mask].copy().reset_index(drop=True)

print(f"Fest Heads count: {len(fest_heads_df)}")
print(f"Executives count: {len(executives_df)}")
print(f"Heads & Co-Heads count: {len(heads_coheads_df)}")

Fest Heads count: 3
Executives count: 8
Heads & Co-Heads count: 24

## Push Data directly to PostgreSQL with Image Paths

In [6]:
# Connection details for PostgreSQL database
DB_CONFIG = {
    "dbname": "chrononexia",
    "user": "postgres",
    "password": "",
    "host": "localhost",
    "port": 5432
}

def push_df_to_postgres(df, table_name, db_config):
    insert_query = f"""
        INSERT INTO {table_name} (name, position, academic_year, comment, description, image_url)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (name) DO UPDATE SET
            position = EXCLUDED.position,
            academic_year = EXCLUDED.academic_year,
            comment = EXCLUDED.comment,
            description = EXCLUDED.description,
            image_url = EXCLUDED.image_url;
    """
    
    records = []
    for _, row in df.iterrows():
        name = str(row[col_name]).strip() if pd.notna(row[col_name]) else None
        pos = str(row[col_pos]).strip() if pd.notna(row[col_pos]) else None
        year = str(row[col_year]).strip() if pd.notna(row[col_year]) else None
        comment = str(row[col_comment]).strip() if pd.notna(row[col_comment]) else None
        desc = str(row[col_desc]).strip() if pd.notna(row[col_desc]) else None
        img = str(row[col_img]).strip() if pd.notna(row[col_img]) and row[col_img] is not None else None
        records.append((name, pos, year, comment, desc, img))
    
    with psycopg.connect(**db_config) as conn:
        with conn.cursor() as cur:
            cur.executemany(insert_query, records)
        conn.commit()
    print(f"Successfully pushed {len(records)} records into PostgreSQL table '{table_name}'")

# Execute database push
push_df_to_postgres(fest_heads_df, "fest_heads", DB_CONFIG)
push_df_to_postgres(executives_df, "executives", DB_CONFIG)
push_df_to_postgres(heads_coheads_df, "heads_and_coheads", DB_CONFIG)

Successfully pushed 3 records into PostgreSQL table 'fest_heads'
Successfully pushed 8 records into PostgreSQL table 'executives'
Successfully pushed 24 records into PostgreSQL table 'heads_and_coheads'