In [16]:
import pandas as pd
import numpy as np
import os
import re
import psycopg

In [17]:
data = pd.read_csv("/Users/anshumaansoni/PycharmProjects/chrononexia/db/scripts/OC data (Responses) - Form Responses 1-2.csv")
display(data)

,Timestamp,Full Name,Your Position in Symbitech,Academic Year,"A comment you may want to give, related to the event. ( Like a yearbook comment, will be used on website and insta posts. )","Describe yourself in about 30 words, and why you're a great fit in the symbitech OC",Image
0,7/22/2026 20:19:39,Aarushi Sathyanarayanan,Fest Head,Third Year,We made it. Don't ask how. (OR) Every great id...,"Part planner, part problem-solver, full-time c...",5114
1,7/28/2026 21:49:36,Aditya Shete,Head of Finance,Third Year,The best memories were never part of the sylla...,I'm an enthusiastic and dependable team player...,Aditya.Shete.EventsHead
2,7/28/2026 10:13:16,Aditya Singh,Executive Head - Sponsorship & PR,Third Year,"When life gives me a lemon, I'd make it a prog...",Having a prior experience in events and sponso...,5123
3,7/22/2026 22:55:28,Anirudh Singh,Design Head,Third Year,Glad to be a part of it!,"Creative, reliable, and proactive, I enjoy wor...",5511
4,7/28/2026 16:11:18,Anuj Korpakwad,PR/Media - Head,Third Year,I love to capture 📷,Im just a normal guy who just loves to shoot a...,NaN
5,7/22/2026 22:26:59,Anushka Gupta,Co head hospitality,Second Year,"To all the people, the chaos, and the memo...","I believe I am a great fit as I’m organized, d...",4449
6,7/23/2026 12:14:29,Arush Kapur,Fest Head,Third Year,Ctrl + Z doesn’t work in life. I checked !!,"I lead with initiative, stay calm under pressu...",5113
7,7/22/2026 11:40:44,Atharva Somawanshi,Executive Hospitality,Third Year,NaN,I can do this task as i was the executive for ...,Executive_Hospitality_Atharva Somawanshi
8,7/22/2026 11:46:14,Eklavya Singh Shekhawat,Executive member Logistics,Third Year,"Where ideas spark, technology inspires, and me...",Proactive team player who enjoys taking respon...,5140
9,7/22/2026 12:44:04,Ishaan Chand,Co Head,Second Year,Sleep is temporary. SymbiTech screenshots are ...,"I'm Ishaan, a student of AIML, who thrives on ...",5570
10,7/22/2026 22:12:17,Kavish Nag,Documentation Executive,Third Year,The best stories are yet to be written. Excite...,"I am someone who likes to stay involved, help ...",5122
11,7/22/2026 12:52:36,Kavya Prashant Ahire,Event Co-Head,Second Year,"Came for the tech, stayed for the chaos, and s...","I’m a people person who loves taking charge, b...",5552
12,7/27/2026 14:27:36,Madhav Menaria,Hospitality executive,Third Year,Ye dil maange more attendance,"I play chess, run for fun and like making thin...",5120
13,7/22/2026 11:54:49,Madhur Sahay,Co-head logistics,Second Year,An event where tech and fun collides. Few days...,I have already volunteered for the event befor...,5503
14,7/27/2026 14:39:48,Mahek Mishra,Co-head Hospitality,Third Year,"“Some experiences become stories, and some sto...",I’m a proactive and dependable leader who enjo...,5488
15,7/23/2026 19:29:37,Mantavya Anand,Design Executive,Third Year,Why take the high road when the scenic one has...,"I say yes first, then spend the next few days ...",5121
16,7/22/2026 23:05:44,Mehar Jaspal,Documentation Co-head,Second Year,1. The only days that make still going to coll...,Im a great fit because I do my job quickly eno...,5493
17,7/27/2026 12:33:03,Mishti Kinker,Events Head,Third Year,"Not just an event, but a collection of laughte...","I'm someone who loves getting involved, meetin...",NaN
18,7/22/2026 23:42:08,Navya Joshi,Finance Executive,Third Year,"Less “YOLO,” more “ROI”.","I count memories, but I budget in rupees. Reli...",5133
19,7/27/2026 14:22:41,Nilay Bhatia,Fest Head,Third Year,You don’t realise you are living in the gold o...,You’ll see for yourself : )),5107
20,7/22/2026 22:27:40,Ninad Kulkarni,Executive Head Logistics,Third Year,NaN,As a third-year student and Executive Head of ...,5136
21,7/27/2026 14:11:27,Parth sarathi Giri,Hospitality head,Third Year,Onwards and upwards,"A dedicated learner who takes initiative, work...",HOSPITALITY HEAD PARTH
22,7/27/2026 11:38:07,Rachit Jajoo,Design Co-Head,Second Year,Ctrl + S your memories. You never know when yo...,Ideas are easy. Execution is everything. I bri...,NaN
23,7/22/2026 22:24:48,Revanth Sai Sreerangam,Co head finance,Third Year,Journey or destination? I choose people coz wh...,"Curious, patient, and people-oriented. I enjoy...",5478
24,7/22/2026 22:37:53,Samriddhi Chadha,Co-Head,Second Year,NaN,"I am very eager to interact, communicate, lead...",5510
25,7/22/2026 12:05:22,Shreyas wani,Finance co-head,Second Year,Build something worth remembering.\n,"I take ownership, stay dependable under pressu...",5469
26,7/22/2026 12:16:16,Shruti Hore,Design Co Head,Third Year,Core memory unlocked 🫶🫶,"Organized, creative, and always down to help. ...",5483
27,7/22/2026 15:32:39,Shubh Vishwanath Pachling,Finance Head,Third Year,NaN,Im a mechanical engineering student who likes ...,5517
28,7/28/2026 15:39:36,Siddhi Bajpai,Events Executive,Third Year,"“When SymbiTech gives you a stage, make sure...",Hey! I’m Siddhi Bajpai a professional chaos co...,NaN
29,7/24/2026 19:03:52,Siya Joshi,Events Co-Head,Third Year,You miss 100% of the shots you don’t take.,I think I’m a good fit for the SymbITech Organ...,5514
30,7/23/2026 11:29:17,Sparsh Srivastava,PR HEAD,Third Year,"Unfiltered,Unapologetic,Unmissable.","Student entrepreneur, Founder of CareSaathi, p...",Sparsh_Srivastava_Sponsorship&PR Head
31,7/22/2026 11:56:28,Suryansh Singh Rathod,Co-head Logistics,Second Year,"""We were the load balancers of Symbitech — kee...",One of the important character trait about me ...,5495
32,7/27/2026 14:28:09,Uday Pratap Gupta,"Co-Head, Sponsorship & PR",Second Year,\nCode. Create. Connect. Repeat. See you at Sy...,I am a Computer Science student who enjoys sol...,4955
33,7/22/2026 12:07:52,Uday pratap gupta,Co-head,Second Year,NaN,I am a hardworking and creative person. I like...,4955
34,7/23/2026 11:18:16,Vanya Puranik,Finance Co-head,Third Year,Great events aren’t remembered for being perfe...,"I’m a responsible, detail oriented, and collab...",5473
35,7/28/2026 9:53:27,Vardhan Shah,"Co-Head - Sponsors, PR, Media",Third Year,"I don't count memories by days, I count them b...","I'm Vardhan Shah, co-head, PR & Sponsors team....",5461
36,7/22/2026 11:52:11,Wani Kolhey,Website Head,Third Year,NaN,"Good design isn't just seen, it's experienced....",5522
37,7/22/2026 22:37:48,Yatharth Kaul,Executive member- events,Third Year,The event ends. The legacy doesn’t.,"I enjoy being involved, taking ownership, and ...",5132

In [18]:
# Clean up unnecessary timestamp column if present
if "Timestamp" in data.columns:
    data = data.drop(columns=["Timestamp"])

## Processing Image references and linking to actual photoshoot files

In [19]:
photoshoot_dir = os.path.join(os.getcwd(), "src/assets/Photoshoot") if not os.path.isabs("src/assets/Photoshoot") else "src/assets/Photoshoot"
if not os.path.exists(photoshoot_dir):
    photoshoot_dir = "/Users/anshumaansoni/PycharmProjects/chrononexia/src/assets/Photoshoot"
list_dir = os.listdir(photoshoot_dir)

file_map = {}
for f in list_dir:
    if f.startswith(".") or not ("." in f):
        continue
    base, ext = os.path.splitext(f)
    file_map[f.lower()] = f
    file_map[base.lower()] = f
    if base.lower().startswith("img_"):
        file_map[base[4:].lower()] = f

def resolve_image_path(raw_val):
    if pd.isna(raw_val):
        return None
    val_str = str(raw_val).strip()
    if "parth" in val_str.lower():
        return "src/assets/Photoshoot/HOSPITALITY_HEAD_PARTH.jpg"
    if val_str.lower() in file_map:
        return f"src/assets/Photoshoot/{file_map[val_str.lower()]}"
    clean_val = val_str.replace("IMG_", "").lower()
    if clean_val in file_map:
        return f"src/assets/Photoshoot/{file_map[clean_val]}"
    for key, fname in file_map.items():
        if clean_val == key or (len(clean_val) > 3 and clean_val in key):
            return f"src/assets/Photoshoot/{fname}"
    return None

data["Image_Path"] = data["Image"].apply(resolve_image_path)
display(data[["Full Name", "Image", "Image_Path"]])

,Full Name,Image,Image_Path
0,Aarushi Sathyanarayanan,5114,src/assets/Photoshoot/IMG_5114.JPG
1,Aditya Shete,Aditya.Shete.EventsHead,src/assets/Photoshoot/Aditya.Shete.EventsHead.png
2,Aditya Singh,5123,src/assets/Photoshoot/IMG_5123.JPG
3,Anirudh Singh,5511,src/assets/Photoshoot/IMG_5511.JPG
4,Anuj Korpakwad,NaN,NaN
5,Anushka Gupta,4449,NaN
6,Arush Kapur,5113,src/assets/Photoshoot/IMG_5113.JPG
7,Atharva Somawanshi,Executive_Hospitality_Atharva Somawanshi,src/assets/Photoshoot/Executive_Hospitality_At...
8,Eklavya Singh Shekhawat,5140,src/assets/Photoshoot/IMG_5140.JPG
9,Ishaan Chand,5570,src/assets/Photoshoot/IMG_5570.JPG
10,Kavish Nag,5122,src/assets/Photoshoot/IMG_5122.JPG
11,Kavya Prashant Ahire,5552,src/assets/Photoshoot/IMG_5552.JPG
12,Madhav Menaria,5120,src/assets/Photoshoot/IMG_5120.JPG
13,Madhur Sahay,5503,src/assets/Photoshoot/IMG_5503.JPG
14,Mahek Mishra,5488,src/assets/Photoshoot/IMG_5488.JPG
15,Mantavya Anand,5121,src/assets/Photoshoot/IMG_5121.JPG
16,Mehar Jaspal,5493,src/assets/Photoshoot/IMG_5493.JPG
17,Mishti Kinker,NaN,NaN
18,Navya Joshi,5133,src/assets/Photoshoot/IMG_5133.JPG
19,Nilay Bhatia,5107,src/assets/Photoshoot/IMG_5107.JPG
20,Ninad Kulkarni,5136,src/assets/Photoshoot/IMG_5136.JPG
21,Parth sarathi Giri,HOSPITALITY HEAD PARTH,src/assets/Photoshoot/HOSPITALITY HEAD PARTH
22,Rachit Jajoo,NaN,NaN
23,Revanth Sai Sreerangam,5478,src/assets/Photoshoot/IMG_5478.JPG
24,Samriddhi Chadha,5510,src/assets/Photoshoot/IMG_5510.JPG
25,Shreyas wani,5469,src/assets/Photoshoot/IMG_5469.JPG
26,Shruti Hore,5483,src/assets/Photoshoot/IMG_5483.JPG
27,Shubh Vishwanath Pachling,5517,src/assets/Photoshoot/IMG_5517.JPG
28,Siddhi Bajpai,NaN,NaN
29,Siya Joshi,5514,src/assets/Photoshoot/IMG_5514.JPG
30,Sparsh Srivastava,Sparsh_Srivastava_Sponsorship&PR Head,src/assets/Photoshoot/Sparsh_Srivastava_Sponso...
31,Suryansh Singh Rathod,5495,src/assets/Photoshoot/IMG_5495.JPG
32,Uday Pratap Gupta,4955,src/assets/Photoshoot/IMG_4955.JPG
33,Uday pratap gupta,4955,src/assets/Photoshoot/IMG_4955.JPG
34,Vanya Puranik,5473,src/assets/Photoshoot/IMG_5473.JPG
35,Vardhan Shah,5461,src/assets/Photoshoot/IMG_5461.JPG
36,Wani Kolhey,5522,src/assets/Photoshoot/IMG_5522.JPG
37,Yatharth Kaul,5132,src/assets/Photoshoot/IMG_5132.JPG

## Extracting Fest Heads, Executives, and Heads & Co-Heads

In [20]:
col_name = "Full Name"
col_pos = "Your Position in Symbitech"
col_year = "Academic Year"
col_comment = "A comment you may want to give, related to the event. ( Like a yearbook comment, will be used on website and insta posts. )"
col_desc = "Describe yourself in about 30 words, and why you're a great fit in the symbitech OC"
col_img = "Image_Path"

# 1. Fest Heads
fest_heads_df = data[data[col_pos].astype(str).str.strip().str.lower() == "fest head"].copy().reset_index(drop=True)

# 2. Executives
executives_df = data[data[col_pos].astype(str).str.contains("executive", case=False, na=False)].copy().reset_index(drop=True)

# 3. Heads & Co-Heads (excluding Fest Head & Executives)
exclude_mask = data[col_pos].astype(str).str.strip().str.lower().eq("fest head") | data[col_pos].astype(str).str.contains("executive", case=False, na=False)
heads_coheads_df = data[~exclude_mask].copy().reset_index(drop=True)

print(f"Fest Heads count: {len(fest_heads_df)}")
print(f"Executives count: {len(executives_df)}")
print(f"Heads & Co-Heads count: {len(heads_coheads_df)}")

Fest Heads count: 3
Executives count: 10
Heads & Co-Heads count: 25

## Push Data directly to PostgreSQL with Image Paths

In [21]:
import os
import psycopg

# Connection details for PostgreSQL database
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/chrononexia")

def push_df_to_postgres(df, table_name, conn_info):
    insert_query = f"""
        INSERT INTO {table_name} (name, position, academic_year, comment, description, image_url)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (name) DO UPDATE SET
            position = EXCLUDED.position,
            academic_year = EXCLUDED.academic_year,
            comment = EXCLUDED.comment,
            description = EXCLUDED.description,
            image_url = EXCLUDED.image_url;
    """
    
    records = []
    for _, row in df.iterrows():
        name = str(row[col_name]).strip() if pd.notna(row[col_name]) else None
        pos = str(row[col_pos]).strip() if pd.notna(row[col_pos]) else None
        year = str(row[col_year]).strip() if pd.notna(row[col_year]) else None
        comment = str(row[col_comment]).strip() if pd.notna(row[col_comment]) else None
        desc = str(row[col_desc]).strip() if pd.notna(row[col_desc]) else None
        img = str(row[col_img]).strip() if pd.notna(row[col_img]) and row[col_img] is not None else None
        if name:
            records.append((name, pos, year, comment, desc, img))
    
    try:
        with psycopg.connect(conn_info) as conn:
            with conn.cursor() as cur:
                cur.executemany(insert_query, records)
            conn.commit()
        print(f"Successfully pushed {len(records)} records into PostgreSQL table '{table_name}'")
    except Exception as e:
        # Try fallback connection parameters if connection string failed
        db_config = {"dbname": "chrononexia", "user": "postgres", "password": "", "host": "localhost", "port": 5432}
        with psycopg.connect(**db_config) as conn:
            with conn.cursor() as cur:
                cur.executemany(insert_query, records)
            conn.commit()
        print(f"Successfully pushed {len(records)} records into PostgreSQL table '{table_name}' via fallback config")

# Execute database push
push_df_to_postgres(fest_heads_df, "fest_heads", DATABASE_URL)
push_df_to_postgres(executives_df, "executives", DATABASE_URL)
push_df_to_postgres(heads_coheads_df, "heads_and_coheads", DATABASE_URL)

Successfully pushed 3 records into PostgreSQL table 'fest_heads'
Successfully pushed 10 records into PostgreSQL table 'executives'
Successfully pushed 25 records into PostgreSQL table 'heads_and_coheads'

In [22]:
print(data)

                     Full Name         Your Position in Symbitech  \
0      Aarushi Sathyanarayanan                          Fest Head
1                Aditya Shete                    Head of Finance
2                 Aditya Singh  Executive Head - Sponsorship & PR
3                Anirudh Singh                        Design Head
4              Anuj Korpakwad                     PR/Media - Head
5                Anushka Gupta               Co head hospitality
6                  Arush Kapur                          Fest Head
7          Atharva Somawanshi               Executive Hospitality
8      Eklavya Singh Shekhawat        Executive member Logistics
9                 Ishaan Chand                            Co Head
10                  Kavish Nag           Documentation Executive
11        Kavya Prashant Ahire                      Event Co-Head
12              Madhav Menaria              Hospitality executive
13                Madhur Sahay                  Co-head logistics
14                Mahek Mishra                Co-head Hospitality
15             Mantavya Anand                   Design Executive
16                Mehar Jaspal              Documentation Co-head
17              Mishti Kinker                         Events Head
18                 Navya Joshi                 Finance Executive
19               Nilay Bhatia                           Fest Head
20              Ninad Kulkarni           Executive Head Logistics
21          Parth sarathi Giri                   Hospitality head
22                Rachit Jajoo                     Design Co-Head
23     Revanth Sai Sreerangam                     Co head finance
24            Samriddhi Chadha                           Co-Head
25                Shreyas wani                    Finance co-head
26                 Shruti Hore                     Design Co Head
27  Shubh Vishwanath Pachling                        Finance Head
28              Siddhi Bajpai                   Events Executive
29                  Siya Joshi                     Events Co-Head
30           Sparsh Srivastava                            PR HEAD
31       Suryansh Singh Rathod                  Co-head Logistics
32           Uday Pratap Gupta          Co-Head, Sponsorship & PR
33          Uday pratap gupta                             Co-head
34               Vanya Puranik                    Finance Co-head
35               Vardhan Shah       Co-Head - Sponsors, PR, Media
36                Wani Kolhey                       Website Head
37               Yatharth Kaul          Executive member- events

   Academic Year  \
0     Third Year
1     Third Year
2     Third Year
3     Third Year
4     Third Year
5    Second Year
6     Third Year
7     Third Year
8     Third Year
9    Second Year
10    Third Year
11   Second Year
12    Third Year
13   Second Year
14    Third Year
15    Third Year
16   Second Year
17    Third Year
18    Third Year
19    Third Year
20    Third Year
21    Third Year
22   Second Year
23    Third Year
24   Second Year
25   Second Year
26    Third Year
27    Third Year
28    Third Year
29    Third Year
30    Third Year
31   Second Year
32   Second Year
33   Second Year
34    Third Year
35    Third Year
36    Third Year
37    Third Year

   A comment you may want to give, related to the event. ( Like a yearbook comment, will be used on website and insta posts. )  \
0   We made it. Don't ask how. (OR) Every great id...
1   The best memories were never part of the sylla...
2   When life gives me a lemon, I'd make it a prog...
3                            Glad to be a part of it!
4                                 I love to capture 📷
5       To all the people, the chaos, and the memo...
6         Ctrl + Z doesn’t work in life. I checked !!
7                                                 NaN
8   Where ideas spark, technology inspires, and me...
9   Sleep is temporary. SymbiTech screenshots are ...
10  The best stories are yet to be written. Excite...
11  Came for the tech, stayed for the chaos, and s...
12                      Ye dil maange more attendance
13  An event where tech and fun collides. Few days...
14  “Some experiences become stories, and some sto...
15  Why take the high road when the scenic one has...
16  1. The only days that make still going to coll...
17  Not just an event, but a collection of laughte...
18                           Less “YOLO,” more “ROI”.
19  You don’t realise you are living in the gold o...
20                                                NaN
21                                Onwards and upwards
22  Ctrl + S your memories. You never know when yo...
23  Journey or destination? I choose people coz wh...
24                                                NaN
25               Build something worth remembering.\n
26                            Core memory unlocked 🫶🫶
27                                                NaN
28    “When SymbiTech gives you a stage, make sure...
29         You miss 100% of the shots you don’t take.
30                Unfiltered,Unapologetic,Unmissable.
31  "We were the load balancers of Symbitech — kee...
32  \nCode. Create. Connect. Repeat. See you at Sy...
33                                                NaN
34  Great events aren’t remembered for being perfe...
35  I don't count memories by days, I count them b...
36                                                NaN
37               The event ends. The legacy doesn’t.

   Describe yourself in about 30 words, and why you're a great fit in the symbitech OC  \
0   Part planner, part problem-solver, full-time c...
1   I'm an enthusiastic and dependable team player...
2   Having a prior experience in events and sponso...
3   Creative, reliable, and proactive, I enjoy wor...
4   Im just a normal guy who just loves to shoot a...
5   I believe I am a great fit as I’m organized, d...
6   I lead with initiative, stay calm under pressu...
7   I can do this task as i was the executive for ...
8   Proactive team player who enjoys taking respon...
9   I'm Ishaan, a student of AIML, who thrives on ...
10  I am someone who likes to stay involved, help ...
11  I’m a people person who loves taking charge, b...
12  I play chess, run for fun and like making thin...
13  I have already volunteered for the event befor...
14  I’m a proactive and dependable leader who enjo...
15  I say yes first, then spend the next few days ...
16  Im a great fit because I do my job quickly eno...
17  I'm someone who loves getting involved, meetin...
18  I count memories, but I budget in rupees. Reli...
19                       You’ll see for yourself : ))
20  As a third-year student and Executive Head of ...
21  A dedicated learner who takes initiative, work...
22  Ideas are easy. Execution is everything. I bri...
23  Curious, patient, and people-oriented. I enjoy...
24  I am very eager to interact, communicate, lead...
25  I take ownership, stay dependable under pressu...
26  Organized, creative, and always down to help. ...
27  Im a mechanical engineering student who likes ...
28  Hey! I’m Siddhi Bajpai a professional chaos co...
29  I think I’m a good fit for the SymbITech Organ...
30  Student entrepreneur, Founder of CareSaathi, p...
31  One of the important character trait about me ...
32  I am a Computer Science student who enjoys sol...
33  I am a hardworking and creative person. I like...
34  I’m a responsible, detail oriented, and collab...
35  I'm Vardhan Shah, co-head, PR & Sponsors team....
36  Good design isn't just seen, it's experienced....
37  I enjoy being involved, taking ownership, and ...

                                       Image  \
0                                       5114
1                    Aditya.Shete.EventsHead
2                                       5123
3                                       5511
4                                        NaN
5                                       4449
6                                       5113
7   Executive_Hospitality_Atharva Somawanshi
8                                       5140
9                                       5570
10                                      5122
11                                      5552
12                                      5120
13                                      5503
14                                      5488
15                                      5121
16                                      5493
17                                       NaN
18                                      5133
19                                      5107
20                                      5136
21                    HOSPITALITY HEAD PARTH
22                                       NaN
23                                      5478
24                                      5510
25                                      5469
26                                      5483
27                                      5517
28                                       NaN
29                                      5514
30     Sparsh_Srivastava_Sponsorship&PR Head
31                                      5495
32                                      4955
33                                      4955
34                                      5473
35                                      5461
36                                      5522
37                                      5132

                                           Image_Path
0                  src/assets/Photoshoot/IMG_5114.JPG
1   src/assets/Photoshoot/Aditya.Shete.EventsHead.png
2                  src/assets/Photoshoot/IMG_5123.JPG
3                  src/assets/Photoshoot/IMG_5511.JPG
4                                                 NaN
5                                                 NaN
6                  src/assets/Photoshoot/IMG_5113.JPG
7   src/assets/Photoshoot/Executive_Hospitality_At...
8                  src/assets/Photoshoot/IMG_5140.JPG
9                  src/assets/Photoshoot/IMG_5570.JPG
10                 src/assets/Photoshoot/IMG_5122.JPG
11                 src/assets/Photoshoot/IMG_5552.JPG
12                 src/assets/Photoshoot/IMG_5120.JPG
13                 src/assets/Photoshoot/IMG_5503.JPG
14                 src/assets/Photoshoot/IMG_5488.JPG
15                 src/assets/Photoshoot/IMG_5121.JPG
16                 src/assets/Photoshoot/IMG_5493.JPG
17                                                NaN
18                 src/assets/Photoshoot/IMG_5133.JPG
19                 src/assets/Photoshoot/IMG_5107.JPG
20                 src/assets/Photoshoot/IMG_5136.JPG
21       src/assets/Photoshoot/HOSPITALITY HEAD PARTH
22                                                NaN
23                 src/assets/Photoshoot/IMG_5478.JPG
24                 src/assets/Photoshoot/IMG_5510.JPG
25                 src/assets/Photoshoot/IMG_5469.JPG
26                 src/assets/Photoshoot/IMG_5483.JPG
27                 src/assets/Photoshoot/IMG_5517.JPG
28                                                NaN
29                 src/assets/Photoshoot/IMG_5514.JPG
30  src/assets/Photoshoot/Sparsh_Srivastava_Sponso...
31                 src/assets/Photoshoot/IMG_5495.JPG
32                 src/assets/Photoshoot/IMG_4955.JPG
33                 src/assets/Photoshoot/IMG_4955.JPG
34                 src/assets/Photoshoot/IMG_5473.JPG
35                 src/assets/Photoshoot/IMG_5461.JPG
36                 src/assets/Photoshoot/IMG_5522.JPG
37                 src/assets/Photoshoot/IMG_5132.JPG